# The name of the application (no spaces)
app_name: specimen_numbers

# A brief description of the app.
description : Given a Postgres "sentences" table, finds all specimen numbers mentioned in that table which are connected to the set of institutions whose abbreviations are currently given in the GDD "museums" dictionary (see it at https://geodeepdive.org/api/dictionaries?dict=museums&show_terms) plus any additional listed in additional_abbrs.txt. Returns a data frame of tuples (docid, sentid, institution, specimen number) which is sent back to Postgres.

# Your first and last name
user: Valerie Syverson

# The NLP product to run the application against
product: NLP352

# Your email
email: vsyverson@gmail.com

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: R

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used
dictionaries: [museums]

terms: []
